name: Callback

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  get-param:
    runs-on: ubuntu-latest
    steps:
      - name: get param
        run: |
          echo "param: ${{ secrets.param }}"